# Generated by Django 6.0.5 on 2026-05-31 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(verbose_name='مقدار تخفیف')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ سفارش')),
                ('max_discount_amount', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر مبلغ تخفیف')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='محدودیت استفاده')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(verbose_name='از تاریخ')),
                ('valid_until', models.DateTimeField(verbose_name='تا تاریخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(blank=True, related_name='discounts', to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
            },
        ),
        migrations.CreateModel(
            name='DiscountUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(verbose_name='شناسه سفارش')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='discounts.discount', verbose_name='کد تخفیف')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_usages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'استفاده از تخفیف',
                'verbose_name_plural': 'استفاده\u200cهای تخفیف',
                'unique_together': {('discount', 'user')},
            },
        ),
    ]
