# Generated by Django 5.2.4 on 2026-06-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discountusage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='discount',
            name='is_birthday_type',
            field=models.BooleanField(default=False, verbose_name='تخفیف تولد'),
        ),
        migrations.AddField(
            model_name='discountusage',
            name='used_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال استفاده'),
        ),
    ]
