# Generated by Django 4.2.17 on 2026-09-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_alter_discountusage_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinBackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع تخفیف')),
                ('value', models.PositiveIntegerField(default=10, verbose_name='مقدار تخفیف')),
                ('valid_days', models.PositiveSmallIntegerField(default=14, help_text='از لحظه\u200cی ارسال پیامک، کد تخفیف تا چند روز معتبر بماند', verbose_name='مدت اعتبار کد (روز)')),
            ],
            options={
                'verbose_name': 'تنظیمات پیامک دلتنگی',
                'verbose_name_plural': 'تنظیمات پیامک دلتنگی',
            },
        ),
    ]
