# Generated by Django 4.2.17 on 2026-09-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_winbacksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='winbacksettings',
            name='max_discount_amount',
            field=models.PositiveIntegerField(blank=True, help_text='برای جلوگیری از تخفیف سنگین روی سفارش\u200cهای بزرگ — فقط برای نوع درصدی معنی دارد؛ خالی یعنی بدون سقف', null=True, verbose_name='حداکثر مبلغ تخفیف (تومان)'),
        ),
    ]
