# Generated by Django 6.0.5 on 2026-07-25 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'انجام شده'), ('no_show', 'حضور نیافت')], db_index=True, default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['-date', 'status'], name='resv_date_status_idx'),
        ),
    ]
