# Generated by Django 6.0.5 on 2026-05-31 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'ناموفق')], default='sent', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'لاگ پیامک',
                'verbose_name_plural': 'لاگ پیامک\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
