# Generated by Django 6.0.5 on 2026-07-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='status',
            field=models.CharField(choices=[('sent', 'ارسال شد'), ('failed', 'ناموفق'), ('skipped', 'غیرفعال (موقتاً خاموش)')], default='sent', max_length=10, verbose_name='وضعیت'),
        ),
    ]
