# Generated by Django 4.2.17 on 2026-08-14 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0002_alter_smslog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, verbose_name='آدرس اشتراک')),
                ('endpoint_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='هش آدرس اشتراک')),
                ('p256dh', models.CharField(max_length=255, verbose_name='کلید p256dh')),
                ('auth', models.CharField(max_length=255, verbose_name='کلید auth')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='مرورگر/دستگاه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اشتراک نوتیفیکیشن',
                'verbose_name_plural': 'اشتراک\u200cهای نوتیفیکیشن',
                'ordering': ['-created_at'],
            },
        ),
    ]
