# Generated by Django 4.2.17 on 2026-09-05 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0016_alter_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnappSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='یکپارچه\u200cسازی با اسنپ\u200cباکس فعال است')),
                ('dispatch_mode', models.CharField(choices=[('manual', 'دستی — فقط با دکمه\u200cی صریح ادمین/سرپرست سالن'), ('auto_on_confirm', 'خودکار — بلافاصله پس از تأیید سفارش'), ('auto_on_ready', 'خودکار — پس از آماده شدن سفارش')], default='manual', max_length=20, verbose_name='نحوه\u200cی ارسال به پیک')),
                ('default_delivery_category', models.CharField(default='bike-without-box', help_text='مثلاً bike-without-box، bike، van — طبق مستندات اسنپ\u200cباکس', max_length=50, verbose_name='دسته\u200cبندی پیش\u200cفرض ارسال')),
                ('store_address', models.CharField(blank=True, max_length=255, verbose_name='آدرس مبدا (کافه)')),
                ('store_latitude', models.CharField(blank=True, max_length=30, verbose_name='عرض جغرافیایی مبدا')),
                ('store_longitude', models.CharField(blank=True, max_length=30, verbose_name='طول جغرافیایی مبدا')),
                ('store_contact_name', models.CharField(blank=True, max_length=100, verbose_name='نام تحویل\u200cدهنده در مبدا')),
                ('store_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس مبدا')),
            ],
            options={
                'verbose_name': 'تنظیمات اسنپ\u200cباکس',
                'verbose_name_plural': 'تنظیمات اسنپ\u200cباکس',
            },
        ),
        migrations.CreateModel(
            name='SnappCourierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapp_order_id', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='شناسه سفارش در اسنپ')),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار تخصیص پیک'), ('ACCEPTED', 'پیک تخصیص یافت'), ('PICKED_UP', 'بسته توسط پیک دریافت شد'), ('DELIVERED', 'تحویل داده شد'), ('CANCELLED', 'لغو شده'), ('PREPENDING', 'در حال ثبت'), ('BATCHED', 'در صف تجمیع'), ('VERIFICATION', 'در انتظار تأیید کد'), ('RESERVED', 'رزرو شده'), ('FAILED', 'ناموفق'), ('BIDDING', 'در حال مزایده')], default='PENDING', max_length=20, verbose_name='وضعیت پیک')),
                ('tracking_url', models.URLField(blank=True, verbose_name='لینک رهگیری زنده')),
                ('delivery_fare', models.PositiveIntegerField(blank=True, null=True, verbose_name='هزینه واقعی پیک (تومان)')),
                ('biker_name', models.CharField(blank=True, max_length=100, verbose_name='نام پیک')),
                ('biker_phone', models.CharField(blank=True, max_length=20, verbose_name='شماره پیک')),
                ('biker_photo_url', models.URLField(blank=True, verbose_name='عکس پیک')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل لغو')),
                ('dispatched_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال به اسنپ')),
                ('last_webhook_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین بروزرسانی از وبهوک')),
                ('raw_last_response', models.JSONField(blank=True, null=True, verbose_name='آخرین پاسخ خام (برای دیباگ)')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapp_courier', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'سفارش پیک اسنپ\u200cباکس',
                'verbose_name_plural': 'سفارش\u200cهای پیک اسنپ\u200cباکس',
                'ordering': ['-dispatched_at'],
            },
        ),
    ]
