# Generated by Django 4.2.17 on 2026-09-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snappsettings',
            name='store_city',
            field=models.CharField(default='dezful', help_text='نام لاتین شهر طبق مستندات اسنپ\u200cباکس، مثلاً dezful', max_length=50, verbose_name='شهر (برای API اسنپ\u200cباکس)'),
        ),
    ]
