# Generated by Django 4.2.17 on 2026-09-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0002_snappsettings_store_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnappFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=255, verbose_name='پیام خطا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'خطای اسنپ\u200cباکس',
                'verbose_name_plural': 'خطاهای اسنپ\u200cباکس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='snappcourierorder',
            name='current_latitude',
            field=models.CharField(blank=True, max_length=30, verbose_name='عرض جغرافیایی لحظه\u200cای پیک'),
        ),
        migrations.AddField(
            model_name='snappcourierorder',
            name='current_longitude',
            field=models.CharField(blank=True, max_length=30, verbose_name='طول جغرافیایی لحظه\u200cای پیک'),
        ),
        migrations.AddField(
            model_name='snappcourierorder',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین بروزرسانی موقعیت'),
        ),
        migrations.AddField(
            model_name='snappcourierorder',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='هر بار که بعد از لغو/ناموفق\u200cشدن دوباره به پیک ارسال شود، یکی اضافه می\u200cشود', verbose_name='تعداد ارسال مجدد'),
        ),
        migrations.AddField(
            model_name='snappsettings',
            name='circuit_breaker_max_failures',
            field=models.PositiveSmallIntegerField(default=5, help_text='بعد از این تعداد خطای پشت\u200cسرهم در بازه\u200cی زیر، یکپارچه\u200cسازی موقتاً غیرفعال می\u200cشود', verbose_name='حداکثر خطای پیاپی مجاز'),
        ),
        migrations.AddField(
            model_name='snappsettings',
            name='circuit_breaker_tripped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان فعال\u200cشدن حالت اضطراری'),
        ),
        migrations.AddField(
            model_name='snappsettings',
            name='circuit_breaker_window_minutes',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='بازه\u200cی زمانی شمارش خطا (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='snappsettings',
            name='default_delivery_category',
            field=models.CharField(default='bike-without-box', help_text='مثلاً bike-without-box، bike، van — طبق مستندات اسنپ\u200cباکس (یا از لیست واقعی زیر انتخاب کنید)', max_length=50, verbose_name='دسته\u200cبندی پیش\u200cفرض ارسال'),
        ),
    ]
