# Generated by Django 4.2.17 on 2026-09-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0003_snappfailurelog_snappcourierorder_current_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snappsettings',
            name='max_delivery_radius_km',
            field=models.PositiveSmallIntegerField(default=15, help_text='آدرس\u200cهای دورتر از این فاصله (خط مستقیم) از مبدا، قابل ثبت نیستند', verbose_name='حداکثر شعاع مجاز ثبت آدرس (کیلومتر)'),
        ),
    ]
