# Generated by Django 4.2.17 on 2026-09-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0004_snappsettings_max_delivery_radius_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snappsettings',
            name='default_delivery_category',
            field=models.CharField(default='bike', help_text='مثلاً bike (با باکس)، bike-without-box، van — طبق مستندات اسنپ\u200cباکس (یا از لیست واقعی زیر انتخاب کنید)', max_length=50, verbose_name='دسته\u200cبندی پیش\u200cفرض ارسال'),
        ),
    ]
