# Generated by Django 4.2.17 on 2026-09-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snapp', '0006_alter_snappcourierorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snappcourierorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار تخصیص پیک'), ('ACCEPTED', 'پیک تخصیص یافت — در راه کافه'), ('ARRIVED_AT_PICK_UP', 'پیک به کافه رسید'), ('PICKED_UP', 'بسته توسط پیک دریافت شد'), ('ARRIVED_AT_DROP_OFF', 'پیک به آدرس مشتری رسید'), ('DELIVERED', 'تحویل داده شد'), ('CANCELLED', 'لغو شده'), ('PREPENDING', 'در حال ثبت'), ('BATCHED', 'در صف تجمیع'), ('VERIFICATION', 'در انتظار تأیید کد'), ('RESERVED', 'رزرو شده'), ('FAILED', 'ناموفق'), ('BIDDING', 'در حال مزایده')], default='PENDING', max_length=20, verbose_name='وضعیت پیک'),
        ),
    ]
