# Generated by Django 6.0.5 on 2026-05-31 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شد'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('delivery_type', models.CharField(choices=[('takeaway', 'تحویل در محل'), ('delivery', 'ارسال با پیک')], default='takeaway', max_length=20, verbose_name='نوع تحویل')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات سفارش')),
                ('total_price', models.PositiveIntegerField(default=0, verbose_name='مبلغ کل')),
                ('delivery_cost', models.PositiveIntegerField(default=0, verbose_name='هزینه ارسال')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ تخفیف')),
                ('final_price', models.PositiveIntegerField(default=0, verbose_name='مبلغ نهایی')),
                ('discount_code', models.CharField(blank=True, max_length=50, verbose_name='کد تخفیف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address', verbose_name='آدرس تحویل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='menu.menuitem', verbose_name='آیتم منو')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'آیتم سفارش',
                'verbose_name_plural': 'آیتم\u200cهای سفارش',
            },
        ),
    ]
