# Generated by Django 5.2.4 on 2026-06-25 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_add_variant_to_orderitem'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='reservations.table', verbose_name='میز'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('takeaway', 'تحویل در محل (برون\u200cبر)'), ('delivery', 'ارسال با پیک'), ('dine_in', 'سرو در کافه')], default='takeaway', max_length=20, verbose_name='نوع تحویل'),
        ),
    ]
