# Generated by Django 6.0.5 on 2026-07-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_table_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='پرداخت شده'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cash', 'پرداخت در محل')], default='online', max_length=10, verbose_name='روش پرداخت'),
        ),
    ]
