# Generated by Django 6.0.5 on 2026-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_status_refactor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='packaging_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه بسته\u200cبندی'),
        ),
    ]
