# Generated by Django 6.0.5 on 2026-07-24 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitemaddon'),
        ('orders', '0006_order_packaging_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام افزودنی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت افزودنی')),
                ('addon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.menuitemaddon', verbose_name='افزودنی')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='orders.orderitem', verbose_name='آیتم سفارش')),
            ],
            options={
                'verbose_name': 'افزودنی سفارش',
                'verbose_name_plural': 'افزودنی\u200cهای سفارش',
            },
        ),
    ]
