# Generated by Django 6.0.5 on 2026-07-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitemaddon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_payment', 'در انتظار پرداخت'), ('paid', 'پرداخت شده — در صف آماده\u200cسازی'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شد'), ('cancelled', 'لغو شده')], db_index=True, default='waiting_payment', max_length=20, verbose_name='وضعیت'),
        ),
    ]
