# Generated by Django 4.2.17 on 2026-08-06 14:21 — دستی برای backfill سفارش‌های موجود ویرایش شد

from django.db import migrations, models


def backfill_order_numbers(apps, schema_editor):
    """
    به سفارش‌های از قبل موجود (که هنوز order_number ندارند) بر اساس تاریخ شمسیِ
    محلیِ ثبت‌شان و ترتیب زمانی، شماره می‌دهد و DailyOrderCounter هر روز را با
    آخرین شماره‌ی صادرشده هم‌گام می‌کند تا سفارش‌های بعدی از همان‌جا ادامه پیدا کنند.
    """
    import jdatetime
    from django.utils import timezone

    Order = apps.get_model('orders', 'Order')
    DailyOrderCounter = apps.get_model('orders', 'DailyOrderCounter')

    counts = {}
    for order in Order.objects.order_by('created_at'):
        local_date = timezone.localtime(order.created_at).date()
        j = jdatetime.date.fromgregorian(date=local_date)
        prefix = f'{j.year:04d}{j.month:02d}{j.day:02d}'
        counts[prefix] = counts.get(prefix, 0) + 1
        order.order_number = f'{prefix}{counts[prefix]}'
        order.save(update_fields=['order_number'])

    for prefix, count in counts.items():
        DailyOrderCounter.objects.update_or_create(
            jalali_date=prefix, defaults={'last_number': count}
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_created_at_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalali_date', models.CharField(max_length=8, unique=True, verbose_name='تاریخ شمسی (YYYYMMDD)')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='آخرین شماره صادرشده')),
            ],
            options={
                'verbose_name': 'شمارنده روزانه سفارش',
                'verbose_name_plural': 'شمارنده‌های روزانه سفارش',
            },
        ),
        # ابتدا بدون unique اضافه می‌شود چون سفارش‌های موجود همه order_number خالی خواهند داشت
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='بر اساس تاریخ شمسی روز ثبت + شماره ترتیبی همان روز — خودکار ساخته می‌شود', max_length=20, verbose_name='شماره سفارش'),
        ),
        migrations.RunPython(backfill_order_numbers, noop_reverse),
        # حالا که همه‌ی ردیف‌ها مقدار یکتا دارند، محدودیت unique اضافه می‌شود
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='بر اساس تاریخ شمسی روز ثبت + شماره ترتیبی همان روز — خودکار ساخته می‌شود', max_length=20, unique=True, verbose_name='شماره سفارش'),
        ),
    ]
