# Generated by Django 4.2.17 on 2026-08-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_dailyordercounter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_payment', 'در انتظار پرداخت'), ('paid', 'تأیید شده — در صف آماده\u200cسازی'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شد'), ('cancelled', 'لغو شده')], db_index=True, default='waiting_payment', max_length=20, verbose_name='وضعیت'),
        ),
    ]
