# Generated by Django 4.2.17 on 2026-08-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='دلیل رد سفارش'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_payment', 'در انتظار پرداخت'), ('pending_confirmation', 'در انتظار تأیید کافه'), ('paid', 'تأیید شده — در صف آماده\u200cسازی'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده تحویل'), ('delivered', 'تحویل داده شد'), ('rejected', 'رد شده توسط کافه'), ('cancelled', 'لغو شده')], db_index=True, default='waiting_payment', max_length=20, verbose_name='وضعیت'),
        ),
    ]
