# Generated by Django 4.2.17 on 2026-08-07 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_order_rejection_reason_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_waiter',
            field=models.ForeignKey(blank=True, help_text='با تأیید یا رد سفارش توسط یک گارسون تنظیم می\u200cشود؛ تا پایان سفارش فقط همان گارسون آن را می\u200cبیند', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='گارسون مسئول'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تحویل'),
        ),
    ]
