# Generated by Django 4.2.17 on 2026-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_approved_at_order_assigned_waiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('takeaway', 'تحویل در محل (بیرون\u200cبر)'), ('delivery', 'ارسال با پیک'), ('dine_in', 'سرو در کافه')], default='takeaway', max_length=20, verbose_name='نوع تحویل'),
        ),
    ]
