# Generated by Django 4.2.17 on 2026-08-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_delivery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cash_reminder_sent_at',
            field=models.DateTimeField(blank=True, help_text='تا این فیلد خالی نشود، دوباره برای همین سفارش یادآوری نقدی ارسال نمی\u200cشود', null=True, verbose_name='زمان ارسال یادآوری نقدی'),
        ),
    ]
