# Generated by Django 4.2.17 on 2026-08-16 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0014_order_cash_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assigned_waiter',
            field=models.ForeignKey(blank=True, help_text='با تأیید یا رد سفارش توسط یک سرپرست سالن تنظیم می\u200cشود؛ تا پایان سفارش فقط همان سرپرست آن را می\u200cبیند', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست سالن مسئول'),
        ),
    ]
