# Generated by Django 4.2.17 on 2026-09-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_order_assigned_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('cash', 'پرداخت در محل'), ('wallet', 'کیف پول')], default='online', max_length=10, verbose_name='روش پرداخت'),
        ),
    ]
