# Generated by Django 4.2.17 on 2026-09-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='walk_in_customer_name',
            field=models.CharField(blank=True, help_text='فقط برای سفارش\u200cهایی که پرسنل مستقیماً برای مشتری حضوری ثبت کرده — سفارش\u200cهای عادی این را خالی می\u200cگذارند چون نام واقعی از حساب کاربری مشتری خوانده می\u200cشود', max_length=100, verbose_name='نام مشتری حضوری'),
        ),
    ]
