# Generated by Django 6.0.5 on 2026-05-31 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='آیکون')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام آیتم')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('discounted_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='تصویر')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('unavailable', 'ناموجود'), ('coming_soon', 'به زودی')], default='available', max_length=20, verbose_name='وضعیت')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='گیاهی')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='کالری')),
                ('preparation_time', models.PositiveIntegerField(default=10, verbose_name='زمان آماده\u200cسازی (دقیقه)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='menu.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'آیتم منو',
                'verbose_name_plural': 'آیتم\u200cهای منو',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='menu/gallery/', verbose_name='تصویر')),
                ('order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='menu.menuitem', verbose_name='آیتم')),
            ],
            options={
                'verbose_name': 'تصویر آیتم',
                'verbose_name_plural': 'تصاویر آیتم',
                'ordering': ['order'],
            },
        ),
    ]
