# Generated by Django 6.0.5 on 2026-06-22 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('discounted_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت با تخفیف')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='menu.menuitem', verbose_name='آیتم')),
            ],
            options={
                'verbose_name': 'نوع آیتم',
                'verbose_name_plural': 'انواع آیتم',
                'ordering': ['order', 'id'],
            },
        ),
    ]
