# Generated by Django 6.0.5 on 2026-07-23 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_add_menuitemvariant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__order', 'category__name', 'order', 'name'], 'verbose_name': 'آیتم منو', 'verbose_name_plural': 'آیتم\u200cهای منو'},
        ),
    ]
