# Generated by Django 6.0.5 on 2026-07-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='menu/thumbnails/', verbose_name='بندانگشتی (خودکار)'),
        ),
    ]
