# Generated by Django 6.0.5 on 2026-07-24 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_image_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام افزودنی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت افزودنی (تومان)')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='menu.menuitem', verbose_name='آیتم')),
            ],
            options={
                'verbose_name': 'افزودنی آیتم',
                'verbose_name_plural': 'افزودنی\u200cهای آیتم',
                'ordering': ['order', 'id'],
            },
        ),
    ]
