# Generated by Django 6.0.5 on 2026-07-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitemaddon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ویژه'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='status',
            field=models.CharField(choices=[('available', 'موجود'), ('unavailable', 'ناموجود'), ('coming_soon', 'به زودی')], db_index=True, default='available', max_length=20, verbose_name='وضعیت'),
        ),
    ]
