# Generated by Django 6.0.5 on 2026-07-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_category_is_active_alter_menuitem_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemimage',
            name='image_thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='menu/gallery/thumbnails/', verbose_name='بندانگشتی (خودکار)'),
        ),
    ]
