# Generated by Django 6.0.5 on 2026-06-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='detail',
            field=models.TextField(blank=True, verbose_name='جزئیات آدرس'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, max_length=50, verbose_name='استان'),
        ),
    ]
