# Generated by Django 5.2.4 on 2026-06-25 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('waiter', 'گارسون'), ('admin', 'مدیر')], default='customer', max_length=20, verbose_name='نقش'),
        ),
        migrations.CreateModel(
            name='WaiterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage_orders', models.BooleanField(default=True, verbose_name='مدیریت سفارشات')),
                ('can_manage_reservations', models.BooleanField(default=False, verbose_name='مدیریت رزروها')),
                ('can_manage_tables', models.BooleanField(default=False, verbose_name='مدیریت میزها')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiter_permissions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دسترسی گارسون',
                'verbose_name_plural': 'دسترسی\u200cهای گارسون',
            },
        ),
    ]
