# Generated by Django 5.2.4 on 2026-06-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_role_waiterpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان ثبت تاریخ تولد'),
        ),
    ]
