# Generated by Django 6.0.5 on 2026-06-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_birthday_user_birthday_set_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='food_interests',
            field=models.CharField(blank=True, max_length=255, verbose_name='علایق غذایی'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'آقا'), ('female', 'خانم')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'مجرد'), ('married', 'متاهل')], max_length=10, verbose_name='وضعیت تأهل'),
        ),
    ]
