# Generated by Django 4.2.17 on 2026-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_food_interests_user_gender_user_marital_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waiterpermission',
            options={'verbose_name': 'دسترسی سرپرست سالن', 'verbose_name_plural': 'دسترسی\u200cهای سرپرست سالن'},
        ),
        migrations.AddField(
            model_name='waiterpermission',
            name='can_force_close_cafe',
            field=models.BooleanField(default=False, verbose_name='بستن فوری کافه'),
        ),
        migrations.AddField(
            model_name='waiterpermission',
            name='can_manage_menu_availability',
            field=models.BooleanField(default=False, verbose_name='مدیریت موجودی منو'),
        ),
        migrations.AddField(
            model_name='waiterpermission',
            name='can_view_own_performance',
            field=models.BooleanField(default=False, verbose_name='مشاهده عملکرد خود'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'مشتری'), ('waiter', 'سرپرست سالن'), ('admin', 'مدیر')], default='customer', max_length=20, verbose_name='نقش'),
        ),
    ]
