# Generated by Django 4.2.17 on 2026-09-04 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_waiterpermission_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_note',
            field=models.TextField(blank=True, help_text='فقط برای ادمین/کارکنان قابل مشاهده است، به خود کاربر نشان داده نمی\u200cشود', verbose_name='یادداشت داخلی ادمین'),
        ),
    ]
