# Generated by Django 4.2.17 on 2026-09-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, verbose_name='طول جغرافیایی'),
        ),
    ]
