# Generated by Django 4.2.17 on 2026-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_address_latitude_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterpermission',
            name='can_view_customer_contact_info',
            field=models.BooleanField(default=False, help_text='نام، شماره تماس و آدرس مشتری در کارت سفارش نمایش داده شود', verbose_name='مشاهده اطلاعات تماس مشتری'),
        ),
    ]
