# Generated by Django 4.2.17 on 2026-09-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_waiterpermission_can_view_customer_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='waiterpermission',
            name='can_take_walk_in_orders',
            field=models.BooleanField(default=False, help_text='دسترسی به پنل سفارش\u200cگیری حضوری برای مشتریانی که داخل اپلیکیشن سفارش نمی\u200cدهند', verbose_name='ثبت سفارش حضوری'),
        ),
    ]
