# Generated by Django 4.2.17 on 2026-09-03 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0016_alter_order_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال بودن بازگشت وجه')),
                ('cashback_percentage', models.PositiveIntegerField(default=0, help_text='بعد از تکمیل (تحویل) هر سفارش، این درصد از مبلغ نهایی به کیف\u200cپول مشتری برمی\u200cگردد', verbose_name='درصد بازگشت وجه')),
                ('min_order_amount', models.PositiveIntegerField(default=0, verbose_name='حداقل مبلغ سفارش برای بازگشت وجه')),
            ],
            options={
                'verbose_name': 'تنظیمات باشگاه مشتریان',
                'verbose_name_plural': 'تنظیمات باشگاه مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0, verbose_name='موجودی (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'کیف پول',
                'verbose_name_plural': 'کیف پول\u200cها',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('topup', 'شارژ از درگاه'), ('cashback', 'بازگشت وجه سفارش'), ('order_payment', 'پرداخت سفارش'), ('admin_adjustment', 'تنظیم دستی ادمین')], max_length=20, verbose_name='نوع تراکنش')),
                ('amount', models.IntegerField(verbose_name='مبلغ (تومان)')),
                ('balance_after', models.PositiveIntegerField(verbose_name='موجودی پس از تراکنش')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.order', verbose_name='سفارش مرتبط')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet', verbose_name='کیف پول')),
            ],
            options={
                'verbose_name': 'تراکنش کیف پول',
                'verbose_name_plural': 'تراکنش\u200cهای کیف پول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTopup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('status', models.CharField(choices=[('init', 'شروع شده'), ('pending', 'در انتظار تأیید درگاه'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='init', max_length=20, verbose_name='وضعیت')),
                ('authority', models.CharField(blank=True, max_length=100, verbose_name='کد Authority زرین\u200cپال')),
                ('ref_id', models.CharField(blank=True, max_length=100, verbose_name='کد پیگیری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallet_topups', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شارژ کیف پول',
                'verbose_name_plural': 'شارژهای کیف پول',
                'ordering': ['-created_at'],
            },
        ),
    ]
