# Generated by Django 4.2.17 on 2026-09-04 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'تراکنش کیف پول', 'verbose_name_plural': 'تراکنش\u200cهای کیف پول'},
        ),
    ]
