# Generated by Django 6.0.5 on 2026-07-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafereview',
            name='comment',
            field=models.TextField(blank=True, verbose_name='نظر'),
        ),
    ]
