# Generated by Django 4.2.17 on 2026-09-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0017_order_walk_in_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, help_text='خالی بماند یعنی فقط نام کافه (از تنظیمات اطلاعات کافه) چاپ شود', max_length=200, verbose_name='متن بالای فیش')),
                ('footer_text', models.CharField(default='با تشکر 🌹', max_length=200, verbose_name='متن پایین فیش')),
                ('show_customer_name', models.BooleanField(default=True, verbose_name='نمایش نام مشتری روی فیش')),
                ('show_customer_phone', models.BooleanField(default=False, verbose_name='نمایش شماره تماس مشتری روی فیش')),
            ],
            options={
                'verbose_name': 'تنظیمات فیش چاپی',
                'verbose_name_plural': 'تنظیمات فیش چاپی',
            },
        ),
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'در انتظار چاپ'), ('printed', 'چاپ شد')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('printed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان چاپ')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_job', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'صف چاپ فیش',
                'verbose_name_plural': 'صف چاپ فیش',
                'ordering': ['created_at'],
            },
        ),
    ]
