# Generated by Django 6.0.5 on 2026-07-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='card_hash',
            field=models.CharField(blank=True, max_length=100, verbose_name='هش کارت'),
        ),
        migrations.AddField(
            model_name='payment',
            name='card_pan',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره کارت (Mask)'),
        ),
    ]
