# Generated by Django 6.0.5 on 2026-07-25 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_created_at_alter_order_status'),
        ('payments', '0003_payment_init_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('init', 'شروع شده'), ('pending', 'در انتظار تأیید درگاه'), ('success', 'موفق'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], db_index=True, default='init', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payment_status_created_idx'),
        ),
    ]
