# Generated by Django 5.2.4 on 2026-06-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'دوشنبه'), (1, 'سه\u200cشنبه'), (2, 'چهارشنبه'), (3, 'پنجشنبه'), (4, 'جمعه'), (5, 'شنبه'), (6, 'یکشنبه')], unique=True, verbose_name='روز هفته')),
                ('is_open', models.BooleanField(default=True, verbose_name='باز')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='ساعت باز شدن')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='ساعت بسته شدن')),
            ],
            options={
                'verbose_name': 'ساعات کاری',
                'verbose_name_plural': 'ساعات کاری هفتگی',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاریخ')),
                ('is_closed', models.BooleanField(default=True, verbose_name='تعطیل')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='ساعت باز شدن')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='ساعت بسته شدن')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'روز خاص',
                'verbose_name_plural': 'روزهای خاص',
                'ordering': ['date'],
            },
        ),
    ]
