# Generated by Django 6.0.5 on 2026-06-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_deliverysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='است', max_length=100, verbose_name='نام کافه')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='شعار کافه')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='آیدی اینستاگرام')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'اطلاعات کافه',
                'verbose_name_plural': 'اطلاعات کافه',
            },
        ),
    ]
