# Generated by Django 6.0.5 on 2026-06-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_cafeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_reservation_hours', models.PositiveIntegerField(default=3, help_text='کاربران می\u200cتوانند حداکثر تا این تعداد ساعت میز رزرو کنند', verbose_name='حداکثر ساعت رزرو میز')),
            ],
            options={
                'verbose_name': 'تنظیمات رزرو',
                'verbose_name_plural': 'تنظیمات رزرو',
            },
        ),
    ]
