# Generated by Django 6.0.5 on 2026-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_reservationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='تصویر')),
                ('focal_x', models.PositiveSmallIntegerField(default=50, verbose_name='نقطه کانونی افقی (٪)')),
                ('focal_y', models.PositiveSmallIntegerField(default=50, verbose_name='نقطه کانونی عمودی (٪)')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان (اختیاری)')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='لینک (اختیاری)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع نمایش')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان نمایش')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بنر تبلیغاتی',
                'verbose_name_plural': 'بنرهای تبلیغاتی',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
