# Generated by Django 6.0.5 on 2026-07-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='delivery_packaging_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه بسته\u200cبندی سفارش ارسالی (تومان)'),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='takeaway_packaging_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='هزینه بسته\u200cبندی سفارش بیرون\u200cبر (تومان)'),
        ),
    ]
