# Generated by Django 6.0.5 on 2026-07-24 23:08

from django.db import migrations, models


def copy_instagram_to_sociallink(apps, schema_editor):
    """آیدی اینستاگرام قبلی (اگر ثبت شده بود) را به رکورد جدید SocialLink منتقل می‌کند."""
    CafeInfo = apps.get_model('business', 'CafeInfo')
    SocialLink = apps.get_model('business', 'SocialLink')
    info = CafeInfo.objects.first()
    if info and getattr(info, 'instagram', ''):
        SocialLink.objects.create(
            platform='instagram', account=info.instagram, order=0, is_active=True,
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_deliverysettings_delivery_packaging_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('twitter', 'ایکس (توییتر)'), ('linkedin', 'لینکدین'), ('youtube', 'یوتیوب'), ('tiktok', 'تیک\u200cتاک'), ('website', 'وب\u200cسایت / سایر')], max_length=20, verbose_name='نوع شبکه')),
                ('account', models.CharField(help_text='برای «وب\u200cسایت» آدرس کامل را وارد کنید؛ برای بقیه فقط آیدی (بدون @)', max_length=200, verbose_name='آیدی / اکانت')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه\u200cهای اجتماعی',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(copy_instagram_to_sociallink, noop_reverse),
        migrations.RemoveField(
            model_name='cafeinfo',
            name='instagram',
        ),
    ]
