# Generated by Django 4.2.17 on 2026-08-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_sociallink_remove_cafeinfo_instagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeinfo',
            name='name',
            field=models.CharField(default='رز کافه', max_length=100, verbose_name='نام کافه'),
        ),
    ]
