# Generated by Django 4.2.17 on 2026-08-06 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0002_alter_reservation_status_and_more'),
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_approved', 'تأیید سفارش'), ('order_rejected', 'رد سفارش'), ('order_status_changed', 'تغییر وضعیت سفارش'), ('cash_collected', 'وصول نقدی'), ('reservation_confirmed', 'تأیید رزرو'), ('reservation_completed', 'اتمام رزرو'), ('reservation_no_show', 'عدم حضور مشتری'), ('reservation_cancelled', 'لغو رزرو')], max_length=30, verbose_name='نوع اکشن')),
                ('detail', models.CharField(max_length=255, verbose_name='توضیح')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='orders.order', verbose_name='سفارش')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='reservations.reservation', verbose_name='رزرو')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
            ],
            options={
                'verbose_name': 'گزارش فعالیت کارمند',
                'verbose_name_plural': 'گزارش فعالیت کارکنان',
                'ordering': ['-created_at'],
            },
        ),
    ]
