# Generated by Django 4.2.17 on 2026-08-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactionlog',
            name='action',
            field=models.CharField(choices=[('order_approved', 'تأیید سفارش'), ('order_rejected', 'رد سفارش'), ('order_status_changed', 'تغییر وضعیت سفارش'), ('cash_collected', 'وصول نقدی'), ('reservation_confirmed', 'تأیید رزرو'), ('reservation_completed', 'اتمام رزرو'), ('reservation_no_show', 'عدم حضور مشتری'), ('reservation_cancelled', 'لغو رزرو'), ('cafe_force_closed', 'بستن فوری کافه'), ('cafe_reopened', 'بازکردن مجدد کافه')], max_length=30, verbose_name='نوع اکشن'),
        ),
    ]
