# Generated by Django 4.2.17 on 2026-09-05 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_activity', '0003_alter_staffactionlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffactionlog',
            name='action',
            field=models.CharField(choices=[('order_approved', 'تأیید سفارش'), ('order_rejected', 'رد سفارش'), ('order_status_changed', 'تغییر وضعیت سفارش'), ('cash_collected', 'وصول نقدی'), ('reservation_confirmed', 'تأیید رزرو'), ('reservation_completed', 'اتمام رزرو'), ('reservation_no_show', 'عدم حضور مشتری'), ('reservation_cancelled', 'لغو رزرو'), ('cafe_force_closed', 'بستن فوری کافه'), ('cafe_reopened', 'بازکردن مجدد کافه'), ('wallet_admin_adjustment', 'تنظیم دستی کیف\u200cپول'), ('snapp_circuit_breaker_reset', 'فعال\u200cسازی مجدد اسنپ\u200cباکس')], max_length=30, verbose_name='نوع اکشن'),
        ),
    ]
